package inventory.model;
// Generated Dec 1, 2020, 11:28:51 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private int id;
	private String actionName;
	private Integer qty;
	private Integer productId;
	private Date createDate;
	private Date updateDate;
	private Integer type;
	private BigDecimal price;

	public History() {
	}

	public History(int id) {
		this.id = id;
	}

	public History(int id, String actionName, Integer qty, Integer productId, Date createDate, Date updateDate,
			Integer type, BigDecimal price) {
		this.id = id;
		this.actionName = actionName;
		this.qty = qty;
		this.productId = productId;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.type = type;
		this.price = price;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
